# Generated by Django 5.1.6 on 2025-03-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric')], max_length=20)),
                ('transmission', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], max_length=20)),
                ('body_type', models.CharField(choices=[('sedan', 'Sedan'), ('SUV', 'SUV'), ('hatchback', 'Hatchback')], max_length=30)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('vin_number', models.CharField(blank=True, max_length=17, null=True, unique=True)),
            ],
        ),
    ]
