# Generated by Django 5.1.6 on 2025-03-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='mileage',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='auto',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
