# Generated by Django 5.1.6 on 2025-03-12 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
        ('auto', '0003_alter_auto_mileage_alter_auto_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='auto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auto.auto'),
        ),
    ]
